package Random;// Generated by Selenium IDE

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.Test;

import java.util.*;
public class RequestpackageTest {
  private WebDriver driver;
  JavascriptExecutor js;
  @AfterMethod
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
  }
  @AfterMethod
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void requestpackage() {
    driver.get("https://b2e.travware.com/signin");
    driver.manage().window().setSize(new Dimension(1920, 1080));
    driver.findElement(By.name("email")).sendKeys("b2e.travware@travware.com");
    driver.findElement(By.name("password")).sendKeys("password");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector("div:nth-child(4) .w-full .text-xs")).click();
    driver.findElement(By.linkText("Create Request package")).click();
    {
      WebElement element = driver.findElement(By.id(":rd:-form-item"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id(":ra:-form-item")).click();
    driver.findElement(By.id(":ra:-form-item")).sendKeys("hassan");
    {
      WebElement element = driver.findElement(By.id(":rb:-form-item"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("html")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".space-y-2:nth-child(2) > select"));
      dropdown.findElement(By.xpath("//option[. = 'Active']")).click();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".\\__variable_2dbf9b"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
  }
}
